theme: jekyll-theme-cayman
title: Ing. M.Sc.<br> Michael Johann Patalas
logo: images/me.jpg
description: Ing. M.Sc.<br> Michael Johann Patalas<br>Freelancer with over <b>10 years</b> of professional experience in Software Development and Architecture!
