theme: jekyll-theme-minimal
title: Ing. M.Sc. Michael Johann Patalas
logo: images/me.jpg
description: Freelancer with over <b>10 years</b> of professional experience in Software Development and Architecture!
