theme: jekyll-theme-minimal
title: Ing. M.Sc. Michael Johann Patalas
logo: images/me.jpg
description: Over 10 years of professional experience in Software Development and Architecture!<br /><br />After completing my bachelor and master degree in computer science (M. Sc. Ing.), I worked in various software companies as a software developer and most recently as a software systems architect.<br /><br />Since 2018 freelancer for companies from Switzerland, Austria, Poland and Germany.<br /><br />\nWith full commitment, a team player with expert knowledge.
